# Generated by Django 5.2.8 on 2026-06-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='duration',
            field=models.CharField(default='Not Specified', max_length=100),
            preserve_default=False,
        ),
    ]
