# Generated by Django 5.2.8 on 2026-06-07 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_experience_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='duration',
        ),
        migrations.AddField(
            model_name='experience',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 1, 1)),
            preserve_default=False,
        ),
    ]
